name: protgps
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=2.16=mkl
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - captum==0.7.0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - filelock=3.13.1=pyhd8ed1ab_0
  - gmp=6.3.0=h59595ed_0
  - gmpy2=2.1.2=py38h793c122_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=13.2.0=h807b86a_5
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.8.0.2=0
  - libsqlite=3.45.1=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - markupsafe=2.1.5=py38h01eb140_0
  - mkl=2020.2=256
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - networkx=3.1=pyhd8ed1ab_0
  - openssl=3.2.1=hd590300_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.8.15=he550d4f_1_cpython
  - python_abi=3.8=4_cp38
  - pytorch=2.0.0=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - setuptools=69.1.0=pyhd8ed1ab_1
  - sympy=1.12=pypyh9d50eac_103
  - torchtriton=2.0.0=py38
  - typing_extensions=4.9.0=pyha770c72_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - absl-py==2.1.0
      - cachetools==5.3.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comet-ml==3.28.1
      - configobj==5.0.8
      - docker-pycreds==0.4.0
      - dulwich==0.21.7
      - everett==3.3.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==2.28.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.62.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - markdown==3.5.2
      - numpy==1.23.4
      - nvidia-ml-py3==7.352.0
      - oauthlib==3.2.2
      - openpyxl==3.1.2
      - packaging==23.2
      - pandas==2.0.3
      - pathtools==0.1.2
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - promise==2.3
      - protobuf==3.20.1
      - protpy==1.2.1
      - psutil==5.9.8
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydeprecate==0.3.2
      - python-dateutil==2.8.2
      - pytorch-lightning==1.6.4
      - pytz==2024.1
      - pyyaml==6.0.1
      - rdkit==2022.9.5
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - scikit-learn==1.0.1
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentry-sdk==1.40.5
      - setproctitle==1.3.3
      - shortuuid==1.0.11
      - six==1.16.0
      - smmap==5.0.1
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.3.0
      - tqdm==4.62.3
      - urllib3==2.2.1
      - wandb==0.12.19
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - wurlitzer==3.0.3
      - zipp==3.17.0
